### ISSUE TITLE
Learn-Lti - [ Failed to deploy Function App [ AssignmentLearnContent ] ]

### ISSUE THREAD

**Issue by RaedTaha** [microsoft/Learn-LTI#163]
when deploying reached step 10 and got an error

=============================================================
STEP #10 - Installing the backend
=============================================================

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 403, in enable_zip_deploy_functionapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 536, in remove_remote_build_app_settings
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1019, in validate_app_settings_in_scm
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 81, in call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/utils.py", line 77, in call
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1038, in _get_app_settings_from_scm
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
AttributeError: 'str' object has no attribute 'value'
To open an issue, please run: 'az feedback'
Transcript stopped, output file is C:\Learn-Lti\Learn-LTI\deployment\Log\Transcript-14-10-2021-12-04-34.log
Press any Key to Exit:

**Comment by leestott** [comment]
@RaedTaha so this is error is typically associated with not having the correct prerequisites installed https://github.com/microsoft/Learn-LTI/blob/main/docs/TROUBLESHOOTING.md

Ensure you have the following installed and rebooted this typical issues is Azure CLI not being installed.

To begin, you will need:

To begin, you will need:
- [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest?WT.mc_id=learnlti-github-cxa)
- [DotNet Core SDK](https://dotnet.microsoft.com/download?WT.mc_id=learnlti-github-cxa)
- [Node.js](https://nodejs.org/en/download/)
- [Powershell](https://docs.microsoft.com/powershell/scripting/install/installing-powershell?view=powershell-7?WT.mc_id=learnlti-github-cxa)
- [Git](https://git-scm.com/downloads)
- An Azure subscription

**Comment by leestott** [comment]
@RaedTaha  If you transaction log file it will show a more indepth error

**Comment by leestott** [comment]
So the Transaction log shows the issues a issue just deploying the function app to the created resources..

[ 10/14/2021 8:27:08 PM ] - [ERROR] - Exception.Message [ Failed to deploy Function App [ AssignmentLearnContent ] ]
[ 10/14/2021 8:27:08 PM ] - [ERROR] - Exception.Type [ System.Management.Automation.RuntimeException ]

Can you rerun the setup as there is now specific error just a failed to deploy this could of been the result of a network error?
